
dist: trusty

language: java

jdk:
  - oraclejdk8

env:
  matrix:
    - TEAMCITY_VERSION='2018.1'
    - TEAMCITY_VERSION='2019.1'

script:
  - ./gradlew clean build -Pteamcity.api.version=$TEAMCITY_VERSION
